### ISSUE TITLE
Import error latentvelo - AttributeError: module 'jax.random' has no attribute 'KeyArray'

### ISSUE THREAD

**Issue by jayramr** [Spencerfar/LatentVelo#8]
Hi, 

I tried to install letentvelo as per your instructions, but I'm getting error as per below while loading the module

pip install logs as below 

```
python setup.py install
running install
/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing latentvelo.egg-info/PKG-INFO
writing dependency_links to latentvelo.egg-info/dependency_links.txt
writing top-level names to latentvelo.egg-info/top_level.txt
reading manifest file 'latentvelo.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'latentvelo.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/latentvelo
copying build/lib/latentvelo/trainer_anvi_nogcn.py -> build/bdist.linux-x86_64/egg/latentvelo
copying build/lib/latentvelo/dataloader_nogcn.py -> build/bdist.linux-x86_64/egg/latentvelo
copying build/lib/latentvelo/output_results.py -> build/bdist.linux-x86_64/egg/latentvelo
creating build/bdist.linux-x86_64/egg/latentvelo/tools
copying build/lib/latentvelo/tools/trad_velocity.py -> build/bdist.linux-x86_64/egg/latentvelo/tools
copying build/lib/latentvelo/tools/batch_correction.py -> build/bdist.linux-x86_64/egg/latentvelo/tools
copying build/lib/latentvelo/tools/__init__.py -> build/bdist.linux-x86_64/egg/latentvelo/tools
copying build/lib/latentvelo/tools/cell_trajectories.py -> build/bdist.linux-x86_64/egg/latentvelo/tools
copying build/lib/latentvelo/tools/check_velocity.py -> build/bdist.linux-x86_64/egg/latentvelo/tools
copying build/lib/latentvelo/trainer_anvi.py -> build/bdist.linux-x86_64/egg/latentvelo
copying build/lib/latentvelo/ev.py -> build/bdist.linux-x86_64/egg/latentvelo
creating build/bdist.linux-x86_64/egg/latentvelo/models
copying build/lib/latentvelo/models/modules.py -> build/bdist.linux-x86_64/egg/latentvelo/models
copying build/lib/latentvelo/models/velocity_field.py -> build/bdist.linux-x86_64/egg/latentvelo/models
copying build/lib/latentvelo/models/annot_vae_model.py -> build/bdist.linux-x86_64/egg/latentvelo/models
copying build/lib/latentvelo/models/gclayer.py -> build/bdist.linux-x86_64/egg/latentvelo/models
copying build/lib/latentvelo/models/atac_reg_model.py -> build/bdist.linux-x86_64/egg/latentvelo/models
copying build/lib/latentvelo/models/vae_model.py -> build/bdist.linux-x86_64/egg/latentvelo/models
copying build/lib/latentvelo/models/refine_model.py -> build/bdist.linux-x86_64/egg/latentvelo/models
copying build/lib/latentvelo/models/__init__.py -> build/bdist.linux-x86_64/egg/latentvelo/models
copying build/lib/latentvelo/path_regularization.py -> build/bdist.linux-x86_64/egg/latentvelo
copying build/lib/latentvelo/trainer.py -> build/bdist.linux-x86_64/egg/latentvelo
copying build/lib/latentvelo/anvi_dataloader_nogcn.py -> build/bdist.linux-x86_64/egg/latentvelo
copying build/lib/latentvelo/trainer_atac.py -> build/bdist.linux-x86_64/egg/latentvelo
copying build/lib/latentvelo/utils.py -> build/bdist.linux-x86_64/egg/latentvelo
copying build/lib/latentvelo/__init__.py -> build/bdist.linux-x86_64/egg/latentvelo
copying build/lib/latentvelo/tl.py -> build/bdist.linux-x86_64/egg/latentvelo
copying build/lib/latentvelo/anvi_dataloader.py -> build/bdist.linux-x86_64/egg/latentvelo
creating build/bdist.linux-x86_64/egg/latentvelo/plotting
copying build/lib/latentvelo/plotting/__init__.py -> build/bdist.linux-x86_64/egg/latentvelo/plotting
copying build/lib/latentvelo/plotting/metrics.py -> build/bdist.linux-x86_64/egg/latentvelo/plotting
copying build/lib/latentvelo/plotting/scatter_stream.py -> build/bdist.linux-x86_64/egg/latentvelo/plotting
creating build/bdist.linux-x86_64/egg/latentvelo/evaluation
copying build/lib/latentvelo/evaluation/run_metric.py -> build/bdist.linux-x86_64/egg/latentvelo/evaluation
copying build/lib/latentvelo/evaluation/metrics.py -> build/bdist.linux-x86_64/egg/latentvelo/evaluation
copying build/lib/latentvelo/evaluation/__init__.py -> build/bdist.linux-x86_64/egg/latentvelo/evaluation
copying build/lib/latentvelo/pl.py -> build/bdist.linux-x86_64/egg/latentvelo
copying build/lib/latentvelo/collate.py -> build/bdist.linux-x86_64/egg/latentvelo
copying build/lib/latentvelo/atac_dataloader.py -> build/bdist.linux-x86_64/egg/latentvelo
copying build/lib/latentvelo/train.py -> build/bdist.linux-x86_64/egg/latentvelo
copying build/lib/latentvelo/dataloader.py -> build/bdist.linux-x86_64/egg/latentvelo
copying build/lib/latentvelo/velocity_genes.py -> build/bdist.linux-x86_64/egg/latentvelo
copying build/lib/latentvelo/trainer_nogcn.py -> build/bdist.linux-x86_64/egg/latentvelo
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/trainer_anvi_nogcn.py to trainer_anvi_nogcn.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/dataloader_nogcn.py to dataloader_nogcn.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/output_results.py to output_results.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/tools/trad_velocity.py to trad_velocity.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/tools/batch_correction.py to batch_correction.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/tools/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/tools/cell_trajectories.py to cell_trajectories.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/tools/check_velocity.py to check_velocity.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/trainer_anvi.py to trainer_anvi.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/ev.py to ev.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/models/modules.py to modules.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/models/velocity_field.py to velocity_field.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/models/annot_vae_model.py to annot_vae_model.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/models/gclayer.py to gclayer.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/models/atac_reg_model.py to atac_reg_model.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/models/vae_model.py to vae_model.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/models/refine_model.py to refine_model.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/models/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/path_regularization.py to path_regularization.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/trainer.py to trainer.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/anvi_dataloader_nogcn.py to anvi_dataloader_nogcn.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/trainer_atac.py to trainer_atac.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/utils.py to utils.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/tl.py to tl.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/anvi_dataloader.py to anvi_dataloader.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/plotting/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/plotting/metrics.py to metrics.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/plotting/scatter_stream.py to scatter_stream.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/evaluation/run_metric.py to run_metric.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/evaluation/metrics.py to metrics.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/evaluation/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/pl.py to pl.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/collate.py to collate.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/atac_dataloader.py to atac_dataloader.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/train.py to train.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/dataloader.py to dataloader.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/velocity_genes.py to velocity_genes.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/latentvelo/trainer_nogcn.py to trainer_nogcn.cpython-39.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying latentvelo.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying latentvelo.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying latentvelo.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying latentvelo.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/latentvelo-0.1-py3.9.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing latentvelo-0.1-py3.9.egg
Removing /scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/latentvelo-0.1-py3.9.egg
Copying latentvelo-0.1-py3.9.egg to /scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages
Adding latentvelo 0.1 to easy-install.pth file

Installed /scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/latentvelo-0.1-py3.9.egg
Processing dependencies for latentvelo==0.1
Finished processing dependencies for latentvelo==0.1
```

```
pip show latentvelo
Name: latentvelo
Version: 0.1
Summary:
Home-page:
Author: Spencer Farrell
Author-email:
License: MIT
Location: /scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/latentvelo-0.1-py3.9.egg
Requires:
Required-by:
```

```
>>> import latentvelo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/gencore/software/LatentVelo/latentvelo/__init__.py", line 1, in <module>
    import latentvelo.models
  File "/scratch/gencore/software/LatentVelo/latentvelo/models/__init__.py", line 1, in <module>
    from latentvelo.models.vae_model import VAE
  File "/scratch/gencore/software/LatentVelo/latentvelo/models/vae_model.py", line 14, in <module>
    from scvi.distributions import ZeroInflatedNegativeBinomial, NegativeBinomial
  File "/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/scvi/__init__.py", line 11, in <module>
    from . import data, model, external, utils
  File "/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/scvi/data/__init__.py", line 25, in <module>
    from ._preprocessing import (
  File "/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/scvi/data/_preprocessing.py", line 12, in <module>
    from scvi.model._utils import parse_device_args
  File "/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/scvi/model/__init__.py", line 2, in <module>
    from ._amortizedlda import AmortizedLDA
  File "/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/scvi/model/_amortizedlda.py", line 15, in <module>
    from scvi.module import AmortizedLDAPyroModule
  File "/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/scvi/module/__init__.py", line 1, in <module>
    from ._amortizedlda import AmortizedLDAPyroModule
  File "/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/scvi/module/_amortizedlda.py", line 15, in <module>
    from scvi.module.base import PyroBaseModuleClass, auto_move_data
  File "/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/scvi/module/base/__init__.py", line 1, in <module>
    from ._base_module import (
  File "/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/scvi/module/base/_base_module.py", line 14, in <module>
    from flax.training import train_state
  File "/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/flax/training/train_state.py", line 17, in <module>
    import optax
  File "/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/optax/__init__.py", line 17, in <module>
    from optax import contrib
  File "/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/optax/contrib/__init__.py", line 17, in <module>
    from optax.contrib.cocob import cocob
  File "/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/optax/contrib/cocob.py", line 25, in <module>
    from optax._src import base
  File "/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/optax/_src/base.py", line 19, in <module>
    import chex
  File "/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/chex/__init__.py", line 17, in <module>
    from chex._src.asserts import assert_axis_dimension
  File "/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/chex/_src/asserts.py", line 26, in <module>
    from chex._src import asserts_internal as _ai
  File "/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/chex/_src/asserts_internal.py", line 34, in <module>
    from chex._src import pytypes
  File "/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/chex/_src/pytypes.py", line 54, in <module>
    PRNGKey = Union[jax.random.KeyArray, jax.Array]
  File "/scratch/gencore/conda3/envs/scvelo_latentvelo/lib/python3.9/site-packages/jax/_src/deprecations.py", line 54, in getattr
    raise AttributeError(f"module {module!r} has no attribute {name!r}")
AttributeError: module 'jax.random' has no attribute 'KeyArray'

```

Please advise.

**Comment by jayramr** [comment]
Downgraded the version from 0.4.25 to below fixed the issue.

jax==0.4.23 jaxlib==0.4.23
